//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Fresher.Infracstructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Fresher.Infracstructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _{0}Id.
        /// </summary>
        internal static string _ClassNameId {
            get {
                return ResourceManager.GetString("_ClassNameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @m_employeeCode.
        /// </summary>
        internal static string dy_code {
            get {
                return ResourceManager.GetString("dy_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @m_Filter.
        /// </summary>
        internal static string dy_fitler {
            get {
                return ResourceManager.GetString("dy_fitler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @m_employeeId.
        /// </summary>
        internal static string dy_id {
            get {
                return ResourceManager.GetString("dy_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @m_PageInt.
        /// </summary>
        internal static string dy_int {
            get {
                return ResourceManager.GetString("dy_int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @m_PageSize.
        /// </summary>
        internal static string dy_size {
            get {
                return ResourceManager.GetString("dy_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m_{0}Id.
        /// </summary>
        internal static string m_ClassNameId {
            get {
                return ResourceManager.GetString("m_ClassNameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m_{0}.
        /// </summary>
        internal static string m_PropertyName {
            get {
                return ResourceManager.GetString("m_PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_CheckEmployeeCodeExists.
        /// </summary>
        internal static string proc_CheckCodeExist {
            get {
                return ResourceManager.GetString("proc_CheckCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Delete{0}.
        /// </summary>
        internal static string Proc_Delete_className {
            get {
                return ResourceManager.GetString("Proc_Delete_className", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Get{0}ById.
        /// </summary>
        internal static string Proc_Get_classNameById {
            get {
                return ResourceManager.GetString("Proc_Get_classNameById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_GetEmployee_Pagination_Filter.
        /// </summary>
        internal static string Proc_GetEmployee_Pagination_Filter {
            get {
                return ResourceManager.GetString("Proc_GetEmployee_Pagination_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_GetBiggestEmployeeCode.
        /// </summary>
        internal static string Proc_GetEmployeeCode {
            get {
                return ResourceManager.GetString("Proc_GetEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Get{0}s.
        /// </summary>
        internal static string Proc_Gets {
            get {
                return ResourceManager.GetString("Proc_Gets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_GetTotal.
        /// </summary>
        internal static string Proc_GetTotal {
            get {
                return ResourceManager.GetString("Proc_GetTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Insert{0}.
        /// </summary>
        internal static string Proc_Insert_className {
            get {
                return ResourceManager.GetString("Proc_Insert_className", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Update{0}.
        /// </summary>
        internal static string Proc_Update_className {
            get {
                return ResourceManager.GetString("Proc_Update_className", resourceCulture);
            }
        }
    }
}
